[source]
type = "N2C"
socket_path = "./socket"

[intersect]
type = "Origin"

[chain]
type = "preprod"

# [cursor]
# type = "Redis"
# key = "key"
# url = "redis://localhost:6379"
# flush_interval = 1

[sink]
type = "Stdout"
