[source]
type = "N2N"
peers = ["backbone.mainnet.cardanofoundation.org:3001"]

[intersect]
type = "Point"
value = [4493860, "ce7f821d2140419fea1a7900cf71b0c0a0e94afbb1f814a6717cff071c3b6afc"]

[[filters]]
type = "SplitBlock"

[sink]
type = "SqlDb"
connection = "sqlite:./mydatabase.db"
apply_template = "INSERT INTO txs (slot, cbor) VALUES ('{{point.slot}}', X'{{record.hex}}');"
undo_template = "DELETE FROM txs WHERE slot = {{point.slot}}"
reset_template = "DELETE FROM txs WHERE slot > {{point.slot}}"
